### ISSUE TITLE
Current stable version

### ISSUE THREAD

**Issue by troendheim** [SkouRene/HL-phpclient#28]
@borch-inc it seems like you are the current maintainer of this repository.

This repository has not been tagged since 2016 although there has been numerous commits since then. If the current state of master is stable, would you mind creating tagging a new release, so we can use the library?

The current release (1.5.1) is not compatible with PHP 7. We are fetching the library with composer and would like a certain stability on our deps.

**Comment by borch-inc** [comment]
@troendheim sorry for the long response time. 1.5.2 is released.
